### ISSUE TITLE
Panorama View doesn't tile new group frames

### ISSUE THREAD

**Issue by suhr** [photodiode/panorama-view#96] opened 2018-09-08 14:28 UTC

**Comment by projectdelphai** [comment] 2018-09-09 20:38
This project is currently abandoned/not maintained and I can't currently get access to this project to make any changes or fix any issues. If you need any help and want me to fix any issues or add any features, create an issue in my fork of this project [here](https://github.com/projectdelphai/panorama-tab-groups)!

**Comment by devurandom** [comment] 2018-09-23 06:31
Duplicate of #62?

**Closed** 2020-12-08 09:07 UTC
Labels: duplicate
