### ISSUE TITLE
Constant 1 cpu load

### ISSUE THREAD

**Issue by mallniya** [photodiode/panorama-view#99] opened 2018-10-06 23:53 UTC
Hi, I've noticed, that disabling addon is reducing 100%+ cpu utilization with one blank tab to normal low values. I guess that's not how it should work.
Firefox 61.0.1.

**Comment by photodiode** [comment] 2023-03-13 06:30
Closing as it's really old and I can't reproduce.

**Closed by photodiode** 2023-03-13 06:30 UTC
Labels: bug, unknown

**Comment by machitgarha** [comment] 2024-08-05 23:39
Currently this bug seems to be here. Don't know exactly how to reproduce, but it's weird.

Today, I was working, and suddenly my CPU jumped up too much. I tried disabling the extensions, and after disabling Panorama View, CPU slowed down.
